language: generic
sudo: required
services:
  - docker

before_intsall:
  - docker build -t kiranmandhare/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kiranmandhare/docker-react npm run test -- --coverage
